using System.Security.Claims;
using Gather.Api.Data;
using Gather.Api.Domain;
using Gather.Api.Realtime;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
namespace Gather.Api.Features;

public static class RoomEndpoints
{
    public static void MapRooms(this WebApplication app)
    {
        var rooms = app.MapGroup("/api/v1/rooms").ValidateInputs().RequireAuthorization();
        rooms.MapPut("/{id}/members/{userId}/mute", async (string id, string userId, MuteInput input, ClaimsPrincipal p, GatherDb db, AccessService access, RealtimeEvents events) =>
        {
            var actor = await access.Role(id, p.UserId(), "Owner", "Admin", "Moderator");
            var target = await db.Members.FindAsync(id, userId) ?? throw new ApiException(404, "Member not found.");
            CanModerate(actor, target);
            Contracts.Require(input.Minutes is 0 or 5 or 60 or 1440 or 10080, "Choose 5 minutes, 1 hour, 1 day, 1 week, or remove the mute.");
            target.MutedUntil = input.Minutes == 0 ? 0 : Clock.Now + input.Minutes * 60000L;
            await db.SaveChangesAsync();
            await events.RoomChanged(id);
            return Results.NoContent();
        });
        rooms.MapGet("", async (ClaimsPrincipal p, GatherDb db) => { var id = p.UserId(); return await (from r in db.Rooms join m in db.Members on r.Id equals m.RoomId join c in db.Channels on r.Id equals c.RoomId where m.UserId == id select new { r.Id, r.Name, r.Description, r.IsPrivate, r.Color, r.OwnerId, channelId = c.Id, m.Role, memberCount = db.Members.Count(x => x.RoomId == r.Id), unread = db.Messages.Count(x => !x.Deleted && x.ChannelId == c.Id && x.SenderId != id && string.Compare(x.Id, db.Reads.Where(s => s.ChannelId == c.Id && s.UserId == id).Select(s => s.LastMessageId).FirstOrDefault() ?? "") > 0) }).ToListAsync(); });
        rooms.MapGet("/discover", async (string? q, GatherDb db) => { var query = db.Rooms.Where(r => !r.IsPrivate); if (!string.IsNullOrWhiteSpace(q)) query = query.Where(r => r.Name.ToLower().Contains(q.ToLower())); return await query.OrderByDescending(r => r.CreatedAt).Take(100).Select(r => new { r.Id, r.Name, r.Description, r.Color, r.IsPrivate, memberCount = db.Members.Count(m => m.RoomId == r.Id) }).ToListAsync(); });
        rooms.MapPost("", async (RoomInput input, ClaimsPrincipal p, GatherDb db) =>
        {
            Validate(input); var r = new Room { Name = input.Name.Trim(), Description = input.Description.Trim(), IsPrivate = input.IsPrivate, Color = input.Color, OwnerId = p.UserId() };
            var channel = new Channel { RoomId = r.Id }; db.Rooms.Add(r); db.Channels.Add(channel); db.Members.Add(new Member { RoomId = r.Id, UserId = p.UserId(), Role = "Owner" }); await db.SaveChangesAsync(); return new { r.Id, channelId = channel.Id };
        });
        rooms.MapPatch("/{id}", async (string id, RoomInput input, ClaimsPrincipal p, GatherDb db, AccessService access) => { await access.Role(id, p.UserId(), "Owner", "Admin"); Validate(input); var r = (await db.Rooms.FindAsync(id))!; r.Name = input.Name.Trim(); r.Description = input.Description.Trim(); r.Color = input.Color; r.IsPrivate = input.IsPrivate; await db.SaveChangesAsync(); return Results.NoContent(); });
        rooms.MapPost("/{id}/join", async (string id, ClaimsPrincipal p, GatherDb db) => { var r = await db.Rooms.FindAsync(id) ?? throw new ApiException(404, "Room not found."); Contracts.Require(!r.IsPrivate, "This room requires an invitation.", 403); await Join(id, p.UserId(), db); return await db.Channels.Where(c => c.RoomId == id).Select(c => new { channelId = c.Id }).FirstAsync(); });
        rooms.MapGet("/{id}/members", async (string id, ClaimsPrincipal p, GatherDb db, AccessService access, ConnectionRegistry registry) => { await access.Role(id, p.UserId(), "Owner", "Admin", "Moderator", "Member"); var list = await (from m in db.Members join u in db.Users on m.UserId equals u.Id where m.RoomId == id select new { u.Id, u.Username, u.DisplayName, m.Role, m.MutedUntil }).Take(1000).ToListAsync(); var blocked = await db.Blocks.Where(b => b.UserId == p.UserId() || b.TargetId == p.UserId()).Select(b => b.UserId == p.UserId() ? b.TargetId : b.UserId).ToListAsync(); return list.Select(x => new { x.Id, x.Username, x.DisplayName, x.Role, x.MutedUntil, online = !blocked.Contains(x.Id) && registry.Online(x.Id) }); });
        rooms.MapPost("/{id}/leave", async (string id, ClaimsPrincipal p, GatherDb db, AccessService access, RealtimeEvents events) => { var member = await access.Role(id, p.UserId(), "Admin", "Moderator", "Member"); db.Members.Remove(member); await db.SaveChangesAsync(); await events.RoomChanged(id); return Results.NoContent(); });
        rooms.MapDelete("/{id}", async (string id, string confirmation, ClaimsPrincipal p, GatherDb db, AccessService access, RealtimeEvents events) => { await access.Role(id, p.UserId(), "Owner"); var r = (await db.Rooms.FindAsync(id))!; Contracts.Require(confirmation == r.Name, "Type the exact room name to delete it."); var users = await db.Members.Where(m => m.RoomId == id).Select(m => m.UserId).ToListAsync(); db.Rooms.Remove(r); await db.SaveChangesAsync(); await events.Notify(users, "RoomsChanged"); return Results.NoContent(); });
        rooms.MapPatch("/{id}/members/{userId}", async (string id, string userId, RoleInput input, ClaimsPrincipal p, GatherDb db, AccessService access) => { var actor = await access.Role(id, p.UserId(), "Owner", "Admin"); var target = await db.Members.FindAsync(id, userId) ?? throw new ApiException(404, "Member not found."); Contracts.Require(target.Role != "Owner" && target.UserId != p.UserId() && (actor.Role == "Owner" || target.Role != "Admin"), "You cannot change this member’s role.", 403); Contracts.Require(new[] { "Admin", "Moderator", "Member" }.Contains(input.Role) && (actor.Role == "Owner" || input.Role != "Admin"), "Invalid role."); target.Role = input.Role; await db.SaveChangesAsync(); return Results.NoContent(); });
        rooms.MapPost("/{id}/transfer/{userId}", async (string id, string userId, ClaimsPrincipal p, GatherDb db, AccessService access) => { var owner = await access.Role(id, p.UserId(), "Owner"); var target = await db.Members.FindAsync(id, userId) ?? throw new ApiException(404, "Member not found."); Contracts.Require(userId != p.UserId(), "Choose another member."); var r = (await db.Rooms.FindAsync(id))!; owner.Role = "Admin"; target.Role = "Owner"; r.OwnerId = userId; await db.SaveChangesAsync(); return Results.NoContent(); });
        rooms.MapDelete("/{id}/members/{userId}", async (string id, string userId, ClaimsPrincipal p, GatherDb db, AccessService access, RealtimeEvents events) => { var actor = await access.Role(id, p.UserId(), "Owner", "Admin", "Moderator"); var target = await db.Members.FindAsync(id, userId) ?? throw new ApiException(404, "Member not found."); CanModerate(actor, target); db.Members.Remove(target); await db.SaveChangesAsync(); await events.Notify([userId], "RoomsChanged"); return Results.NoContent(); });
        rooms.MapPost("/{id}/bans/{userId}", async (string id, string userId, BanInput input, ClaimsPrincipal p, GatherDb db, AccessService access, RealtimeEvents events) => { var actor = await access.Role(id, p.UserId(), "Owner", "Admin"); var target = await db.Members.FindAsync(id, userId); if (target != null) { CanModerate(actor, target); db.Members.Remove(target); } Contracts.Require(userId != p.UserId() && await db.Users.AnyAsync(u => u.Id == userId), "Invalid member."); if (!await db.Bans.AnyAsync(b => b.RoomId == id && b.UserId == userId)) db.Bans.Add(new Ban { RoomId = id, UserId = userId, Reason = input.Reason[..Math.Min(input.Reason.Length, 500)] }); await db.SaveChangesAsync(); await events.Notify([userId], "RoomsChanged"); return Results.NoContent(); });
        rooms.MapGet("/{id}/bans", async (string id, ClaimsPrincipal p, GatherDb db, AccessService access) => { await access.Role(id, p.UserId(), "Owner", "Admin"); return await (from b in db.Bans join u in db.Users on b.UserId equals u.Id where b.RoomId == id select new { u.Id, u.DisplayName, u.Username, b.Reason }).ToListAsync(); });
        rooms.MapDelete("/{id}/bans/{userId}", async (string id, string userId, ClaimsPrincipal p, GatherDb db, AccessService access) => { await access.Role(id, p.UserId(), "Owner", "Admin"); await db.Bans.Where(b => b.RoomId == id && b.UserId == userId).ExecuteDeleteAsync(); return Results.NoContent(); });
        rooms.MapGet("/{id}/invites", async (string id, ClaimsPrincipal p, GatherDb db, AccessService access) => { await access.Role(id, p.UserId(), "Owner", "Admin"); return await db.Invites.Where(i => i.RoomId == id && !i.Revoked).ToListAsync(); });
        rooms.MapPost("/{id}/invites", async (string id, InviteInput input, ClaimsPrincipal p, GatherDb db, AccessService access) => { await access.Role(id, p.UserId(), "Owner", "Admin"); Contracts.Require(input.Hours is null or 1 or 24 or 168 && input.MaxUses is null or > 0 and <= 1000, "Choose a valid expiry and usage limit."); var i = new Invite { RoomId = id, ExpiresAt = input.Hours == null ? null : Clock.Now + input.Hours.Value * 3600000L, MaxUses = input.MaxUses }; db.Invites.Add(i); await db.SaveChangesAsync(); return i; }).RequireRateLimiting("invite");
        rooms.MapDelete("/{id}/invites/{code}", async (string id, string code, ClaimsPrincipal p, GatherDb db, AccessService access) => { await access.Role(id, p.UserId(), "Owner", "Admin"); await db.Invites.Where(i => i.RoomId == id && i.Code == code).ExecuteUpdateAsync(s => s.SetProperty(i => i.Revoked, true)); return Results.NoContent(); });
        app.MapGet("/api/v1/invites/{code}", async (string code, GatherDb db) => { var i = await ValidInvite(code, db); return await db.Rooms.Where(r => r.Id == i.RoomId).Select(r => new { r.Name, r.Description, r.Color }).FirstAsync(); }).RequireRateLimiting("search");
        app.MapPost("/api/v1/invites/{code}/accept", async (string code, ClaimsPrincipal p, GatherDb db) => { await using var tx = await db.Database.BeginTransactionAsync(System.Data.IsolationLevel.Serializable); var i = await ValidInvite(code, db); if (await db.Members.FindAsync(i.RoomId, p.UserId()) == null) { await Join(i.RoomId, p.UserId(), db); i.Uses++; await db.SaveChangesAsync(); } await tx.CommitAsync(); return await db.Channels.Where(c => c.RoomId == i.RoomId).Select(c => new { channelId = c.Id }).FirstAsync(); }).RequireAuthorization();
    }
    private static void Validate(RoomInput input) { Contracts.Require(input.Name.Trim().Length is > 0 and <= 80 && input.Description.Length <= 500, "Use a room name of 1–80 characters and a description under 500."); Contracts.Require(System.Text.RegularExpressions.Regex.IsMatch(input.Color, "^#[a-fA-F0-9]{6}$"), "Invalid color."); }
    private static void CanModerate(Member actor, Member target) => Contracts.Require(actor.UserId != target.UserId && target.Role != "Owner" && (actor.Role == "Owner" || target.Role != "Admin") && (actor.Role != "Moderator" || target.Role == "Member"), "You cannot moderate this member.", 403);
    private static async Task<Invite> ValidInvite(string code, GatherDb db) { var i = await db.Invites.FindAsync(code); Contracts.Require(i != null && !i.Revoked, "This invitation is unavailable.", 404); Contracts.Require(i!.ExpiresAt == null || i.ExpiresAt > Clock.Now, "This invitation has expired."); Contracts.Require(i.MaxUses == null || i.Uses < i.MaxUses, "This invitation has reached its usage limit."); return i; }
    private static async Task Join(string id, string userId, GatherDb db) { Contracts.Require(!await db.Bans.AnyAsync(b => b.RoomId == id && b.UserId == userId), "You are banned from this room.", 403); if (await db.Members.FindAsync(id, userId) != null) return; Contracts.Require(await db.Members.CountAsync(m => m.RoomId == id) < 1000, "This room is full."); db.Members.Add(new Member { RoomId = id, UserId = userId }); try { await db.SaveChangesAsync(); } catch (DbUpdateException) { db.ChangeTracker.Clear(); if (!await db.Members.AnyAsync(m => m.RoomId == id && m.UserId == userId)) throw; } }
}
